[project]
name = "vla-ra"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "arxiv>=2.4.0",
    "docling>=2.75.0",
    "langgraph>=1.0.10",
    "langgraph-checkpoint>=4.0.1",
    "openai>=1.0.0",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
]
